"""debtor db

Revision ID: 948d5544dc99
Revises: 5651a1e92fca
Create Date: 2020-02-09 15:45:25.792316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948d5544dc99'
down_revision = '5651a1e92fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('notes', sa.String(length=200), nullable=True))
    op.drop_column('payment', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('note', sa.VARCHAR(length=200), nullable=True))
    op.drop_column('payment', 'notes')
    # ### end Alembic commands ###
