"""debtors table

Revision ID: a3a8f9f3040d
Revises: 
Create Date: 2020-02-09 12:27:14.658227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a8f9f3040d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debtor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('ship', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=120), nullable=True),
    sa.Column('key_person', sa.String(length=120), nullable=True),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('credit_aggreement', sa.String(length=120), nullable=True),
    sa.Column('total_credits', sa.Integer(), nullable=True),
    sa.Column('tenor', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debtor_end_date'), 'debtor', ['end_date'], unique=False)
    op.create_index(op.f('ix_debtor_name'), 'debtor', ['name'], unique=True)
    op.create_index(op.f('ix_debtor_start_date'), 'debtor', ['start_date'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main', sa.Integer(), nullable=True),
    sa.Column('interest', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('debtor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['debtor_id'], ['debtor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_payment_date'), 'payment', ['payment_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_payment_date'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_debtor_start_date'), table_name='debtor')
    op.drop_index(op.f('ix_debtor_name'), table_name='debtor')
    op.drop_index(op.f('ix_debtor_end_date'), table_name='debtor')
    op.drop_table('debtor')
    # ### end Alembic commands ###
